In [22]:
#Importing the Libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [23]:
#Load/Read the datasets
df = pd.read_csv(r"C:\Users\VINIT\sales-selected-columns.csv")
df

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72
...,...,...,...,...,...,...,...,...,...,...
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15

In [24]:
df.head()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72

In [25]:
df.tail()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sale_id           1000 non-null   int64
 1   branch            1000 non-null   object
 2   city              1000 non-null   object
 3   customer_type     1000 non-null   object
 4   gender            1000 non-null   object
 5   product_name      1000 non-null   object
 6   product_category  1000 non-null   object
 7   unit_price        1000 non-null   float64
 8   quantity          1000 non-null   int64
 9   tax               1000 non-null   float64
dtypes: float64(2), int64(2), object(6)
memory usage: 78.3+ KB

In [27]:
df.describe()

           sale_id   unit_price     quantity          tax
count  1000.000000  1000.000000  1000.000000  1000.000000
mean    500.500000    10.836110    10.337000     7.758010
std     288.819436     5.775924     6.029908     6.538066
min       1.000000     1.020000     1.000000     0.080000
25%     250.750000     5.867500     5.000000     2.510000
50%     500.500000    10.615000    10.000000     5.870000
75%     750.250000    15.882500    16.000000    11.522500
max    1000.000000    20.980000    20.000000    28.390000

In [28]:
#Define the LabelEncoder
le = LabelEncoder()
df.columns

Index(['sale_id', 'branch', 'city', 'customer_type', 'gender', 'product_name',
       'product_category', 'unit_price', 'quantity', 'tax'],
      dtype='object')

In [29]:
#Transform gender(categorical) to gender(numeric)
df['gender']= le.fit_transform(df['gender'])
df

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,1,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,0,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,0,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,1,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,0,Orange Juice,Beverages,3.50,7,1.72
...,...,...,...,...,...,...,...,...,...,...
995,996,A,New York,Member,0,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,1,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,0,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,0,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,1,Orange Juice,Stationery,4.11,4,1.15

In [30]:
#Independent Variable(x)
x = df[['quantity']]
x

     quantity
0           3
1          10
2          15
3           5
4           7
..        ...
995        11
996         7
997         2
998         4
999         4

[1000 rows x 1 columns]

In [31]:
#Dependent Variable(y)
y = df['tax']
y

0      1.16
1      1.93
2      1.26
3      2.73
4      1.72
       ...
995    1.19
996    1.20
997    2.51
998    4.87
999    1.15
Name: tax, Length: 1000, dtype: float64

In [32]:
#Splitting the data
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)
x_train

     quantity
29         15
535         5
695        19
557         1
836        17
..        ...
106         6
270         1
860        16
435         8
102         9

[800 rows x 1 columns]

In [33]:
x_test

     quantity
521        18
737         8
740         3
660         3
411         6
..        ...
408         2
332         4
208         7
613         6
78         11

[200 rows x 1 columns]

In [34]:
y_train

29     12.99
535     4.38
695     9.92
557     1.09
836    12.83
       ...
106     1.89
270     1.25
860    10.46
435    11.25
102     5.60
Name: tax, Length: 800, dtype: float64

In [35]:
y_test

521    25.49
737     4.45
740     2.08
660     3.21
411     2.71
       ...
408     2.54
332     5.37
208     4.27
613     5.42
78     10.92
Name: tax, Length: 200, dtype: float64

In [36]:
#Create the Model
model = LinearRegression()

In [37]:
#Train the Model
model.fit(x_train,y_train)

LinearRegression()

In [38]:
#Predict the result
y_pred = model.predict(x_test)
y_pred

array([13.13835794,  5.94708171,  2.35144359,  2.35144359,  4.50882646,
        8.10446458,  2.35144359,  4.50882646, 13.13835794,  1.63231597,
       13.85748556,  7.38533696,  1.63231597,  5.94708171,  1.63231597,
        1.63231597,  4.50882646, 13.85748556,  4.50882646, 14.57661319,
       12.41923032, 10.98097507,  1.63231597,  9.54271983, 10.98097507,
       11.7001027 ,  3.07057122, 13.85748556, 13.13835794, 11.7001027 ,
        6.66620933,  9.54271983, 14.57661319, 10.26184745,  7.38533696,
       11.7001027 ,  3.78969884, 10.26184745, 12.41923032,  3.07057122,
        7.38533696, 12.41923032,  9.54271983,  1.63231597,  8.8235922 ,
        5.94708171,  3.07057122, 13.85748556,  2.35144359, 14.57661319,
        0.91318835,  1.63231597,  3.78969884, 10.98097507,  1.63231597,
        2.35144359,  5.94708171,  5.22795409, 13.85748556, 10.26184745,
        5.22795409,  9.54271983, 14.57661319, 13.13835794,  0.91318835,
        4.50882646, 13.13835794, 13.13835794,  1.63231597,  9.54271983,
       10.98097507,  5.94708171,  5.94708171,  6.66620933,  6.66620933,
        4.50882646, 11.7001027 ,  8.10446458,  0.91318835,  3.07057122,
       13.13835794,  5.94708171, 11.7001027 ,  0.91318835,  5.94708171,
        5.22795409,  3.07057122,  4.50882646, 12.41923032,  3.78969884,
        8.10446458,  3.78969884,  1.63231597, 11.7001027 , 14.57661319,
        8.10446458, 12.41923032,  1.63231597,  7.38533696,  9.54271983,
       11.7001027 , 11.7001027 , 13.13835794,  5.22795409,  0.91318835,
        1.63231597, 11.7001027 ,  5.94708171,  3.07057122,  8.10446458,
        9.54271983,  5.94708171, 13.85748556, 13.13835794,  1.63231597,
       10.98097507, 11.7001027 ,  9.54271983,  5.94708171,  1.63231597,
       11.7001027 , 14.57661319,  2.35144359, 13.85748556,  0.91318835,
        9.54271983, 14.57661319, 14.57661319,  9.54271983, 10.26184745,
        8.10446458,  8.10446458,  9.54271983,  8.10446458, 13.13835794,
        7.38533696,  3.07057122,  1.63231597, 11.7001027 , 14.57661319,
        5.94708171, 12.41923032,  0.91318835,  0.91318835, 10.26184745,
       11.7001027 , 14.57661319, 11.7001027 ,  2.35144359, 11.7001027 ,
       11.7001027 ,  8.10446458,  7.38533696,  9.54271983, 13.13835794,
        0.91318835, 12.41923032,  1.63231597,  1.63231597,  1.63231597,
        5.22795409,  3.78969884,  6.66620933,  3.78969884,  9.54271983,
        3.07057122, 10.98097507, 10.98097507,  3.78969884,  3.78969884,
       12.41923032,  7.38533696,  6.66620933,  7.38533696,  6.66620933,
       14.57661319,  3.07057122,  7.38533696, 11.7001027 ,  5.22795409,
        5.94708171,  3.07057122,  8.8235922 , 11.7001027 ,  5.22795409,
       13.13835794,  1.63231597,  5.94708171,  3.07057122, 10.26184745,
        1.63231597, 10.26184745,  1.63231597,  4.50882646,  0.91318835,
        1.63231597,  3.07057122,  5.22795409,  4.50882646,  8.10446458])

In [39]:
#Score of training model
model.score(x_train,y_train)

0.4525677415805245

In [40]:
#Score of testing model
model.score(x_test,y_test)

0.5165791876592918

In [41]:
#Intercept
i=model.intercept_
i

np.float64(0.19406072284383225)

In [42]:
#coefficient
c=model.coef_
c

array([0.71912762])