In [42]:
#Impoting the libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [43]:
#Load/Read the dataset
df=pd.read_csv(r"C:\Users\VINIT\sales-selected-columns.csv")
df

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72
...,...,...,...,...,...,...,...,...,...,...
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15

In [44]:
df.head()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72

In [45]:
df.tail()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sale_id           1000 non-null   int64
 1   branch            1000 non-null   object
 2   city              1000 non-null   object
 3   customer_type     1000 non-null   object
 4   gender            1000 non-null   object
 5   product_name      1000 non-null   object
 6   product_category  1000 non-null   object
 7   unit_price        1000 non-null   float64
 8   quantity          1000 non-null   int64
 9   tax               1000 non-null   float64
dtypes: float64(2), int64(2), object(6)
memory usage: 78.3+ KB

In [47]:
df.describe()

           sale_id   unit_price     quantity          tax
count  1000.000000  1000.000000  1000.000000  1000.000000
mean    500.500000    10.836110    10.337000     7.758010
std     288.819436     5.775924     6.029908     6.538066
min       1.000000     1.020000     1.000000     0.080000
25%     250.750000     5.867500     5.000000     2.510000
50%     500.500000    10.615000    10.000000     5.870000
75%     750.250000    15.882500    16.000000    11.522500
max    1000.000000    20.980000    20.000000    28.390000

In [48]:
#Define the LabelEncoder
le = LabelEncoder()
df.columns

Index(['sale_id', 'branch', 'city', 'customer_type', 'gender', 'product_name',
       'product_category', 'unit_price', 'quantity', 'tax'],
      dtype='object')

In [49]:
#Transform gender(categorical) to gender(numeric)
df['gender']=le.fit_transform(df['gender'])
df

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax
0,1,A,New York,Member,1,Shampoo,Personal Care,5.50,3,1.16
1,2,B,Los Angeles,Normal,0,Notebook,Stationery,2.75,10,1.93
2,3,A,New York,Member,0,Apple,Fruits,1.20,15,1.26
3,4,A,Chicago,Normal,1,Detergent,Household,7.80,5,2.73
4,5,B,Los Angeles,Member,0,Orange Juice,Beverages,3.50,7,1.72
...,...,...,...,...,...,...,...,...,...,...
995,996,A,New York,Member,0,Shampoo,Stationery,1.55,11,1.19
996,997,A,New York,Member,1,Detergent,Personal Care,2.44,7,1.20
997,998,A,New York,Member,0,Shampoo,Stationery,17.92,2,2.51
998,999,A,New York,Member,0,Shampoo,Beverages,17.41,4,4.87
999,1000,A,New York,Normal,1,Orange Juice,Stationery,4.11,4,1.15

In [50]:
#Independent Variable
x=df[['quantity','unit_price']]
x

     quantity  unit_price
0           3        5.50
1          10        2.75
2          15        1.20
3           5        7.80
4           7        3.50
..        ...         ...
995        11        1.55
996         7        2.44
997         2       17.92
998         4       17.41
999         4        4.11

[1000 rows x 2 columns]

In [51]:
#Dependent variable
y=df['tax']
y

0      1.16
1      1.93
2      1.26
3      2.73
4      1.72
       ...
995    1.19
996    1.20
997    2.51
998    4.87
999    1.15
Name: tax, Length: 1000, dtype: float64

In [52]:
#Splitting the data
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)
x_train

     quantity  unit_price
29         15       12.37
535         5       12.52
695        19        7.46
557         1       15.56
836        17       10.78
..        ...         ...
106         6        4.50
270         1       17.89
860        16        9.34
435         8       20.09
102         9        8.89

[800 rows x 2 columns]

In [53]:
x_test

     quantity  unit_price
521        18       20.23
737         8        7.94
740         3        9.92
660         3       15.29
411         6        6.46
..        ...         ...
408         2       18.12
332         4       19.18
208         7        8.71
613         6       12.90
78         11       14.18

[200 rows x 2 columns]

In [54]:
y_train

29     12.99
535     4.38
695     9.92
557     1.09
836    12.83
       ...
106     1.89
270     1.25
860    10.46
435    11.25
102     5.60
Name: tax, Length: 800, dtype: float64

In [55]:
y_test

521    25.49
737     4.45
740     2.08
660     3.21
411     2.71
       ...
408     2.54
332     5.37
208     4.27
613     5.42
78     10.92
Name: tax, Length: 200, dtype: float64

In [56]:
#Create the model
model = LinearRegression()

In [57]:
#Train the model
model.fit(x_train,y_train)

LinearRegression()

In [58]:
#Predict the Result
y_pred=model.predict(x_test)
y_pred

array([20.20429069,  3.8934159 ,  1.54778354,  5.38761776,  1.33056271,
        3.70479719, -1.11221335,  9.64662824, 16.53606917,  6.6088764 ,
       20.11281566,  6.98540826,  2.07544085,  2.79938493, -2.651059  ,
       -2.46514524, -0.20680108, 15.186101  ,  6.18577208, 19.32058877,
        7.16739398, 15.86662437,  8.00322961,  6.2962525 , 15.05146404,
       12.50020695,  7.14097928,  8.14282967, 20.69767721, 15.31036495,
       12.25386647,  8.92049674, 21.3799412 , 15.22874541,  3.01686452,
       11.27031592, -0.76602422, 10.35923498, 14.56819177,  5.21033638,
        0.60713616, 18.41517651,  5.81716704,  0.85985087,  8.26831672,
       12.46690049,  9.47920235, 14.87862824, -1.19086917, 15.40209874,
        5.45615933, -1.19235103,  8.57971753, 10.43937266,  7.32392933,
       -2.89984566,  0.81868832,  4.12790151, 19.04023627, 17.1808399 ,
        7.18832804, 13.11070689, 10.93301795, 10.6797857 , -4.08264671,
        0.62266031, 19.28902294, 16.24289747,  2.87630012, 13.19651324,
        8.70894458, 11.05824623,  6.31744532,  5.66822902, 12.06795271,
        9.75388618, 18.3278883 ,  1.30936989, -5.11947345,  1.11308311,
       17.00085357,  5.70249981,  9.05365184, -2.2235091 ,  9.50658138,
        7.81757461,  7.65581739,  5.07744004, 17.06372648,  8.98729769,
       11.54177726,  7.70735296,  6.43011317,  6.38650443, 14.40102464,
       10.4262947 , 11.45056101,  7.72435897,  7.82202019, 10.49361318,
        6.00037585,  8.24564204,  9.88607696, -0.16241605, -3.94678665,
       -5.39686224, 13.66574322,  4.49406036,  8.07054809,  5.22070939,
        3.14286909, 12.97458807, 11.38916996, 16.05698371, -4.3385839 ,
       18.35500856, 17.90600707, 15.0914035 , 10.65781659,  2.4544189 ,
        9.43262989, 10.3109219 ,  4.23638254, 20.806417  , -1.61571411,
       15.58479002, 17.12537629, 14.8300564 ,  6.18184403,  9.57982729,
        2.85388421,  1.83135852,  3.50754609,  1.58109   , 13.43989   ,
       13.92142165, -3.59196514,  6.82339228, 14.20203291, 12.44177962,
        9.4636782 , 14.66114865,  5.79223421,  4.0546556 ,  9.75143999,
       15.567784  , 11.190437  , 15.3461176 ,  8.01901253,  7.31607323,
       13.67289375, 14.64510697,  1.1791785 , 14.76247915, 13.54714794,
        1.98815264, 10.72120702,  6.94495128,  0.41651806, -1.92885554,
        2.01134485,  3.43848698,  0.61995536, -0.8089274 ,  5.31662999,
        5.61076602, 13.12797167,  6.4422268 , -3.25440841, 10.38880143,
       18.65829451, 10.03153373,  9.67252541,  3.77482062,  4.88882133,
       18.06209562, -1.66847277, 10.40336125,  5.02075334,  0.73855064,
        4.15083496, -3.02707333,  3.09133353, 12.95784082,  6.8379521 ,
        9.07091662, -3.51627304, 12.4454489 ,  2.90786596, 15.82938987,
        7.58849891, 11.98955565, -3.33750981,  4.85577364,  5.52766462,
        6.65893011,  8.92146107,  3.69171923,  5.93550356, 10.61220846])

In [59]:
#Score the training model
model.score(x_train,y_train)

0.857595962409693

In [60]:
#Score the testing model
model.score(x_test,y_test)

0.8683330892027401

In [61]:
#Intercept
i=model.intercept_
i

np.float64(-7.802403785621437)

In [62]:
#Coefficient
c=model.coef_
c

array([0.75228743, 0.71505293])